# Generated by Django 4.0.3 on 2022-04-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenght', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='MyRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='new_app.room')),
                ('my_storage', models.BooleanField()),
            ],
            options={
                'verbose_name': 'MyRoom',
                'verbose_name_plural': 'MyRooms',
            },
            bases=('new_app.room',),
        ),
    ]
