# Generated by Django 4.0.3 on 2022-04-07 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='customer_balance'),
        ),
    ]
