version: "3.8"
services: 
  database:
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE3_DB=db.sqlite3
    volumes:
      - ./data/db:/root/db
  web:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - database
    command: python3 manage.py runserver 0.0.0.0:8000

